import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

const POKE_API_URL = process.env.REACT_APP_POKE_API_URL
const MAX_POKEMON = process.env.REACT_APP_MAX_POKEMON

export const pokeApi = createApi({
  reducerPath: 'pokeApi',
  baseQuery: fetchBaseQuery({ baseUrl: POKE_API_URL }),
  endpoints: (builder) => ({
    getAllOriginalPokemon: () => ({
      query: () => `pokemon?limit=${MAX_POKEMON}`
    }),
    getPokemonById: builder.query({
      query: (id) => `pokemon/${id}`,
    }),
  }),
})

// autogenerated hooks for usage in function components
export const { useGetAllOriginalPokemon, useGetPokemonByIdQuery } = pokeApi